services:
  - type: web
    name: arthavi-api
    env: python
    region: singapore
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1
    envVars:
      - key: RENDER
        value: "true"
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
